# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a71650b072890427a8a45594fefb2de206cfc7ce91879efc04ebe75c310245f3c0300081d129897fbe214e2a21bea33a19937f5f79f3565f306071612fed8ff9

test:
  secret_key_base: 258e3f9090f2460651f2969a6c1fe96cf5cfa51b13ddf496753281c053503347d7481efbb19c74fbb0d06340922fe849f1892f6a0e159c5a7b6d07f42781d8cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
